name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'backend/ballmate-rest/**'

jobs:
  deploy:
    name: Vercel Deployment
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: backend/ballmate-rest
        run: pnpm install

      - name: Generate Prisma Client
        working-directory: backend/ballmate-rest
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build project
        working-directory: backend/ballmate-rest
        run: pnpm run build
      
      - name: Run tests
        working-directory: backend/ballmate-rest
        run: pnpm run test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
